language: python
python:
  - 3.5
  - 3.6
  - 3.7
cache: pip
before_install:
  - pip install pytest
  - pip install coverage
  - pip install codecov
install: pip install -e .
script:
  - pytest
  - coverage report -m
after_success:
  - codecov